### ISSUE TITLE
Vermutung Uebersetzungsfehler "Lizenzfrei"

### ISSUE THREAD

**Issue by wagnerpeer** [codeforosnabrueck/slides#2]
Hallo,

vielen Dank fuer das Bereitstellen deiner Praesentation. Ich habe deine Praesentation aufmerksam verfolgt und mir scheint es, als haette sich auf einer der Folien ein Uebersetzungsfehler eingeschlichen.

Die Aufzaehlung der Punkte, die offene Daten ausmachen, listet als Punkt 8 "Lizenzfrei". Dies waere nahezu unmoeglich, da jeder Datensatz eine Lizenz besitzt, diese unter Umstaenden nur nicht bekannt gemacht wurde oder aber der "Public Domain" angehoert. Ich vermute, dass es "Freie Lizenz" oder "Offene Lizenz" heissen muesste. Ich verweise hier auf die "Open Definition" als Teil der OKFN, die dies sehr anschaulich beschreibt: https://opendefinition.org/od/2.1/en/

Da dies ein starker inhaltlicher Eingriff ist, werde ich dazu nicht unmittelbar einen Pull Request stellen, sondern bitte zunaechst um eine Bewertung durch dich als Autor.

**Comment by joliyea** [comment]
Done.
